ANIMAL_CATEGORY = {
    # Easy / Common animals
    1: [("CAT", "A pet that says meow"),
        ("DOG", "A pet that barks"),
        ("COW", "Gives us milk"),
        ("PIG", "Likes mud"),
        ("RAT", "A rodent"),
        ("FOX", "Clever wild animal"),
        ("HEN", "Lays eggs"),
        ("ANT", "Tiny insect"),
        ("OWL", "Sees at night"),
        ("BAT", "A flying mammal")],

    2: [("LION", "King of the jungle"),
        ("BEAR", "Big furry animal"),
        ("WOLF", "Howls at the moon"),
        ("FROG", "Jumps, says ribbit"),
        ("DEER", "Has antlers"),
        ("DUCK", "Says quack"),
        ("GOAT", "Likes grass"),
        ("SWAN", "Graceful white bird"),
        ("TOAD", "Like a frog"),
        ("CRAB", "Has claws")],

    3: [("HORSE", "You can ride it"),
        ("SHEEP", "Gives us wool"),
        ("MOUSE", "Small rodent"),
        ("TIGER", "Striped big cat"),
        ("ZEBRA", "Striped horse-like"),
        ("PANDA", "Eats bamboo"),
        ("SNAKE", "Slithers on ground"),
        ("EAGLE", "Large bird of prey"),
        ("SHARK", "Big fish with sharp teeth"),
        ("LLAMA", "South American animal")],

    # Medium animals
    4: [("MONKEY", "Loves bananas"),
        ("DONKEY", "Carries loads"),
        ("RABBIT", "Has long ears"),
        ("SPIDER", "Has eight legs"),
        ("TURTLE", "Has a shell"),
        ("PARROT", "Talks like humans"),
        ("SALMON", "Fish that swims upstream"),
        ("JAGUAR", "Spotted big cat"),
        ("GIRAFFE", "Has a long neck"),
        ("BLOBFISH", "Ugly deep-sea fish")],

    5: [("BUFFALO", "Large wild ox"),
        ("LEOPARD", "Spotted big cat"),
        ("GORILLA", "Largest primate"),
        ("PELICAN", "Bird with large beak pouch"),
        ("OSTRICH", "Big bird that can’t fly"),
        ("COYOTE", "Wild dog of North America"),
        ("PIGEON", "Common city bird"),
        ("CAMEL", "Has humps, lives in desert"),
        ("SEAL", "Marine animal that claps"),
        ("OTTER", "Plays in water, cracks shells")],

    6: [("HIPPO", "Huge animal, loves water"),
        ("KANGAROO", "Jumps with a pouch"),
        ("CROCODILE", "Big reptile with sharp teeth"),
        ("KOALA", "Sleeps on eucalyptus trees"),
        ("PEACOCK", "Bird with colorful feathers"),
        ("SQUID", "Has tentacles and ink"),
        ("BISON", "Large shaggy mammal of plains"),
        ("HYENA", "Laughing scavenger"),
        ("ANTELOPE", "Fast animal with horns"),
        ("FALCON", "Very fast bird")],

    # Harder / Exotic animals
    7: [("SLOTH", "Moves very slowly"),
        ("MOLE", "Lives underground"),
        ("TARSIER", "Big-eyed primate"),
        ("IGUANA", "Green lizard"),
        ("SEAHORSE", "Tiny horse-shaped fish"),
        ("WHALE", "Largest animal on Earth"),
        ("DOLPHIN", "Smart marine mammal"),
        ("ORANGUTAN", "Great ape with orange fur"),
        ("CHAMELEON", "Changes color"),
        ("STARFISH", "Sea creature with 5 arms")],

    8: [("LOBSTER", "Red crustacean with claws"),
        ("PORCUPINE", "Covered with quills"),
        ("WALRUS", "Has tusks and whiskers"),
        ("JELLYFISH", "Soft, stings in water"),
        ("MANTA", "Large ray with wings"),
        ("CATERPILLAR", "Turns into a butterfly"),
        ("PANTHER", "Black big cat"),
        ("CARIBOU", "Reindeer of North America"),
        ("EMU", "Big bird from Australia"),
        ("ALBATROSS", "Large sea bird")],

    9: [("HEDGEHOG", "Tiny animal with spines"),
        ("MEERKAT", "Stands on two legs"),
        ("STINGRAY", "Flat fish with tail sting"),
        ("OCTOPUS", "Eight-armed sea creature"),
        ("AXOLOTL", "Smiling salamander"),
        ("ECHIDNA", "Spiny anteater"),
        ("MARKHOR", "Wild goat with spiral horns"),
        ("TAPIR", "Looks like a pig with a trunk"),
        ("DINGO", "Wild dog of Australia"),
        ("NARWHAL", "Whale with a long tusk")]
}

FOOD_CATEGORY = {
    # Easy / Common foods
    1: [("RICE", "Staple food in Asia"),
        ("BREAD", "Made from flour"),
        ("SOUP", "Hot liquid meal"),
        ("CORN", "Yellow kernels"),
        ("CAKE", "Sweet baked dessert"),
        ("FISH", "Lives in water, eaten as food"),
        ("MEAT", "From animals"),
        ("EGGS", "Laid by hens"),
        ("MILK", "White drink from cows"),
        ("BEAN", "Small protein seed")],

    2: [("APPLE", "Keeps the doctor away"),
        ("MANGO", "Tropical sweet fruit"),
        ("PEACH", "Fuzzy fruit"),
        ("GRAPE", "Used for wine"),
        ("LEMON", "Sour yellow fruit"),
        ("ONION", "Makes you cry"),
        ("PIZZA", "Italian flatbread"),
        ("PASTA", "Italian noodles"),
        ("BERRY", "Small juicy fruit"),
        ("CHILI", "Very spicy")],

    3: [("BANANA", "Yellow curved fruit"),
        ("TOMATO", "Red fruit used in salad"),
        ("ORANGE", "Citrus fruit"),
        ("CARROT", "Orange vegetable"),
        ("PEANUT", "Nut in a shell"),
        ("BURGER", "Bread with meat patty"),
        ("COOKIE", "Sweet baked snack"),
        ("HONEY", "Sweet food from bees"),
        ("JUICE", "Drink from fruits"),
        ("SALAD", "Mix of vegetables")],

    # Medium difficulty
    4: [("CHERRY", "Small red fruit"),
        ("PUMPKIN", "Big orange vegetable"),
        ("GARLIC", "Strong-smelling bulb"),
        ("COFFEE", "Bitter morning drink"),
        ("DONUTS", "Sweet fried bread"),
        ("NOODLE", "Long thin pasta"),
        ("BUTTER", "Made from milk"),
        ("SPINACH", "Leafy green vegetable"),
        ("CHEESE", "Made from milk"),
        ("SUGAR", "Sweet crystals")],

    5: [("POTATO", "Used for fries"),
        ("CHICKEN", "Common white meat"),
        ("CHOCOLATE", "Sweet made from cocoa"),
        ("CABBAGE", "Leafy vegetable"),
        ("ICECREAM", "Frozen dessert"),
        ("SANDWICH", "Two breads with filling"),
        ("PANCAKE", "Flat breakfast food"),
        ("CEREAL", "Breakfast grain"),
        ("YOGURT", "Fermented milk"),
        ("SEAFOOD", "Food from the sea")],

    6: [("STRAWBERRY", "Red fruit with seeds outside"),
        ("PINEAPPLE", "Tropical fruit with spiky skin"),
        ("AVOCADO", "Green creamy fruit"),
        ("CUCUMBER", "Green vegetable, often in salad"),
        ("STEAK", "Grilled beef"),
        ("BACON", "Crispy pork slices"),
        ("MUFFIN", "Small baked cake"),
        ("TEA", "Hot drink from leaves"),
        ("SOY", "Bean used for sauce and milk"),
        ("NUTS", "Hard-shelled snack")],

    # Harder, uncommon, or foreign foods
    7: [("WATERMELON", "Big green fruit with red inside"),
        ("KIWI", "Brown fruit with green inside"),
        ("GUAVA", "Tropical fruit with seeds"),
        ("BROCCOLI", "Tree-like vegetable"),
        ("HOTDOG", "Sausage in a bun"),
        ("OMELET", "Egg dish"),
        ("COCOA", "Used to make chocolate"),
        ("SUSHI", "Japanese rice roll"),
        ("CURRY", "Spicy dish from India"),
        ("FRIES", "Potato snack")],

    8: [("PLUM", "Purple fruit"),
        ("RADISH", "Red root vegetable"),
        ("LASAGNA", "Italian layered pasta"),
        ("SAUSAGE", "Ground meat in casing"),
        ("TOFU", "Made from soybeans"),
        ("BISCUIT", "Crispy baked snack"),
        ("RAMEN", "Japanese noodle soup"),
        ("DUMPLING", "Stuffed dough food"),
        ("PEAR", "Sweet green fruit"),
        ("MELON", "Round sweet fruit")],

    9: [("FIG", "Small sweet fruit"),
        ("DATE", "Sweet desert fruit"),
        ("LYCHEE", "Asian fruit with red skin"),
        ("OLIVE", "Used for oil"),
        ("CHILIPEPPER", "Hot red vegetable"),
        ("TACO", "Mexican folded tortilla"),
        ("TEPPANYAKI", "Japanese grilled food"),
        ("CASSAVA", "Root crop for flour"),
        ("TRUFFLE", "Expensive edible fungus"),
        ("ORANGINA", "Citrus drink brand, rare")]
}

PLACE_CATEGORY = {
    1: [("PARK", "Place to play outside"),
        ("MALL", "Shopping center"),
        ("HOME", "Where you live"),
        ("ROOM", "Part of a house"),
        ("FARM", "Where crops grow"),
        ("CITY", "Big town"),
        ("BANK", "Keeps money safe"),
        ("SHOP", "Small store"),
        ("POOL", "Place to swim"),
        ("HALL", "Big room")],

    2: [("RIVER", "Flows with water"),
        ("FIELD", "Open land"),
        ("BEACH", "Sandy shore"),
        ("HOTEL", "Stay when traveling"),
        ("STREET", "Road in a city"),
        ("YARD", "Grass outside a house"),
        ("DOCK", "Where boats stop"),
        ("CAVE", "Natural hole in a hill"),
        ("BARN", "Farm building"),
        ("POND", "Small body of water")],

    3: [("SCHOOL", "Place to study"),
        ("MARKET", "Place to buy things"),
        ("CHURCH", "Place of worship"),
        ("BRIDGE", "Connects two sides"),
        ("MUSEUM", "Keeps history"),
        ("DEPOT", "Where goods are stored"),
        ("PORT", "Where ships load and unload"),
        ("PLAZA", "Open city square"),
        ("SHED", "Small storage house"),
        ("CABIN", "Small wooden house")],

    4: [("CASTLE", "Home of kings"),
        ("FOREST", "Many trees"),
        ("OFFICE", "Place to work"),
        ("TEMPLE", "Sacred building"),
        ("PRISON", "Holds criminals"),
        ("MARKET", "Trading place"),
        ("ARENA", "Sports or shows"),
        ("DOME", "Large roofed hall"),
        ("CAMP", "Temporary shelter"),
        ("PARKING", "Place for cars")],

    5: [("ISLAND", "Land in water"),
        ("STADIUM", "Sports arena"),
        ("TUNNEL", "Underground passage"),
        ("TOWER", "Tall building"),
        ("PALACE", "Home of royalty"),
        ("MARKETPLACE", "Busy trade center"),
        ("HUT", "Small house"),
        ("SQUARE", "Town center"),
        ("FORT", "Military defense place"),
        ("CABARET", "Entertainment club")],

    6: [("VILLAGE", "Small community"),
        ("HOSPITAL", "Doctors work here"),
        ("AIRPORT", "Planes take off"),
        ("STATION", "Trains stop here"),
        ("THEATER", "Watch plays or movies"),
        ("GYMNASIUM", "Sports exercise hall"),
        ("CHAPEL", "Small church"),
        ("HOSTEL", "Cheap lodging"),
        ("DOCKYARD", "Ship repair place"),
        ("TERRACE", "Flat outdoor space")],

    7: [("FACTORY", "Makes products"),
        ("HARBOR", "Where ships dock"),
        ("MARKETS", "Places to buy goods"),
        ("GARDENS", "Where plants grow"),
        ("CHURCHES", "More than one church"),
        ("CAMPUS", "University grounds"),
        ("MARKET HALL", "Indoor trade center"),
        ("LAB", "Place of experiments"),
        ("ARENA", "Large sports venue"),
        ("COURTYARD", "Open space in buildings")],

    8: [("MOUNTAIN", "Tall landform"),
        ("LIBRARY", "Keeps books"),
        ("COTTAGE", "Small house"),
        ("UNIVERSITY", "Place of higher study"),
        ("RESTAURANT", "Place to eat"),
        ("APARTMENT", "Many homes in one building"),
        ("PLAYGROUND", "Children play here"),
        ("CEMETERY", "Where people are buried"),
        ("WAREHOUSE", "Stores goods"),
        ("SUBWAY", "Underground train")],

    9: [("OBSERVATORY", "Where stars are studied"),
        ("SKYSCRAPER", "Very tall building"),
        ("HEADQUARTERS", "Main office"),
        ("MONASTERY", "Where monks live"),
        ("PLANETARIUM", "Show about space"),
        ("CONFERENCE HALL", "Meetings held here"),
        ("COURTHOUSE", "Place of justice"),
        ("AUDITORIUM", "Big meeting hall"),
        ("CONSULATE", "Foreign government office"),
        ("CATACOMBS", "Underground burial site")]
}
